parameters:
#    netgusto_dev_server.example.class: Netgusto\DevServerBundle\Example

services:
#    netgusto_dev_server.example:
#        class: %netgusto_dev_server.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
